const VIDEO_INPUT_EXTENSIONS = [
  '.mp4', '.mov', '.avi', '.mkv', '.webm', '.wmv', '.flv', '.m4v', '.mpg', '.mpeg', '.3gp', '.ts', '.m2ts', '.ogv',
]

const VIDEO_INPUT_ACCEPT = 'video/*,.avi,.mov,.mkv,.webm,.wmv,.flv,.m4v,.mpg,.mpeg,.3gp,.ts,.m2ts,.ogv'

const ARCHIVE_SOURCE_EXTENSIONS = ['*']

export const CONVERSION_OPTIONS = [
  {
    menuGroup: 'pdf',
    type: 'pdf_to_docx',
    route: '/',
    shortTitle: 'PDF → DOCX',
    title: 'PDF → DOCX',
    description:
      'Конвертируйте PDF в редактируемый документ Word. Подходит для отчётов, договоров и сканов с OCR.',
    inputLabel: 'PDF',
    inputExtensions: ['.pdf'],
    inputAccept: '.pdf,application/pdf',
    outputLabel: 'Скачать DOCX',
    outputHint: 'DOCX',
    featureChips: [],
  },
  {
    menuGroup: 'pdf',
    type: 'pdf_to_jpg',
    route: '/pdf-to-jpg',
    shortTitle: 'PDF → JPG',
    title: 'PDF → JPG',
    description:
      'Преобразуйте страницы PDF в JPG-изображения. На выходе вы получите ZIP-архив с изображениями страниц.',
    inputLabel: 'PDF',
    inputExtensions: ['.pdf'],
    inputAccept: '.pdf,application/pdf',
    outputLabel: 'Скачать ZIP (JPG)',
    outputHint: 'ZIP',
    featureChips: [],
  },
  {
    menuGroup: 'pdf',
    type: 'jpg_to_pdf',
    route: '/jpg-to-pdf',
    shortTitle: 'JPG → PDF',
    title: 'JPG → PDF',
    description:
      'Загрузите один или несколько JPG/JPEG и получите единый PDF в правильном порядке.',
    inputLabel: 'JPG/JPEG',
    inputExtensions: ['.jpg', '.jpeg', '.jfif'],
    inputAccept: '.jpg,.jpeg,.jfif,image/jpeg',
    allowMultiple: true,
    outputLabel: 'Скачать PDF',
    outputHint: 'PDF',
    featureChips: [],
  },
  {
    menuGroup: 'pdf',
    type: 'word_to_pdf',
    route: '/word-to-pdf',
    shortTitle: 'WORD → PDF',
    title: 'WORD → PDF',
    description:
      'Преобразуйте документы Word (.docx/.doc/.docm) в PDF с максимально точным сохранением структуры.',
    inputLabel: 'DOC/DOCX',
    inputExtensions: ['.docx', '.doc', '.docm'],
    inputAccept:
      '.doc,.docx,.docm,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    outputLabel: 'Скачать PDF',
    outputHint: 'PDF',
    featureChips: [],
  },

  {
    menuGroup: 'media',
    mediaSection: 'image',
    type: 'heic_to_jpg',
    route: '/heic-to-jpg',
    shortTitle: 'HEIC → JPG',
    title: 'HEIC → JPG',
    description:
      'Преобразуйте фото HEIC/HEIF (iPhone) в JPG для совместимости с Windows, сайтами и мессенджерами.',
    inputLabel: 'HEIC/HEIF',
    inputExtensions: ['.heic', '.heif'],
    inputAccept: '.heic,.heif,image/heic,image/heif',
    outputLabel: 'Скачать JPG',
    outputHint: 'JPG',
    featureChips: [],
  },
  {
    menuGroup: 'media',
    mediaSection: 'image',
    type: 'png_to_webp',
    route: '/png-to-webp',
    shortTitle: 'PNG → WebP',
    title: 'PNG → WebP',
    description:
      'Оптимизируйте изображения для веба: конвертируйте PNG в WebP с хорошим качеством и меньшим размером.',
    inputLabel: 'PNG',
    inputExtensions: ['.png'],
    inputAccept: '.png,image/png',
    outputLabel: 'Скачать WebP',
    outputHint: 'WebP',
    featureChips: [],
  },
  {
    menuGroup: 'media',
    mediaSection: 'image',
    type: 'svg_to_png',
    route: '/svg-to-png',
    shortTitle: 'SVG → PNG',
    title: 'SVG → PNG',
    description:
      'Преобразуйте векторный SVG в PNG для вставки в документы, презентации и отправки заказчику.',
    inputLabel: 'SVG',
    inputExtensions: ['.svg'],
    inputAccept: '.svg,image/svg+xml',
    outputLabel: 'Скачать PNG',
    outputHint: 'PNG',
    featureChips: [],
  },
  {
    menuGroup: 'media',
    mediaSection: 'image',
    type: 'png_to_ico',
    route: '/png-to-ico',
    shortTitle: 'PNG → ICO',
    title: 'PNG → ICO',
    description:
      'Создайте favicon: конвертируйте PNG в ICO для вкладки браузера и ярлыков.',
    inputLabel: 'PNG',
    inputExtensions: ['.png'],
    inputAccept: '.png,image/png',
    outputLabel: 'Скачать ICO',
    outputHint: 'ICO',
    featureChips: [],
  },
  {
    menuGroup: 'media',
    mediaSection: 'image',
    type: 'psd_ai_to_png',
    route: '/psd-ai-to-png',
    shortTitle: 'PSD/AI → PNG',
    title: 'PSD/AI → PNG',
    description:
      'Преобразуйте макеты Photoshop/Illustrator в PNG, чтобы быстро делиться результатом без профессионального ПО.',
    inputLabel: 'PSD/AI',
    inputExtensions: ['.psd', '.ai'],
    inputAccept: '.psd,.ai,image/vnd.adobe.photoshop,application/postscript',
    outputLabel: 'Скачать PNG',
    outputHint: 'PNG',
    featureChips: [],
  },
  {
    menuGroup: 'media',
    mediaSection: 'image',
    type: 'psd_ai_to_jpg',
    route: '/psd-ai-to-jpg',
    shortTitle: 'PSD/AI → JPG',
    title: 'PSD/AI → JPG',
    description:
      'Преобразуйте файлы PSD/AI в JPG для отправки клиентам и публикации в мессенджерах.',
    inputLabel: 'PSD/AI',
    inputExtensions: ['.psd', '.ai'],
    inputAccept: '.psd,.ai,image/vnd.adobe.photoshop,application/postscript',
    outputLabel: 'Скачать JPG',
    outputHint: 'JPG',
    featureChips: [],
  },

  {
    menuGroup: 'media',
    mediaSection: 'video',
    type: 'video_to_mp4',
    route: '/video-to-mp4',
    shortTitle: 'Всё → MP4',
    title: 'Всё → MP4',
    description:
      'Преобразуйте видео разных форматов в MP4 (H.264/AAC) для максимальной совместимости.',
    inputLabel: 'Видео',
    inputExtensions: VIDEO_INPUT_EXTENSIONS,
    inputAccept: VIDEO_INPUT_ACCEPT,
    outputLabel: 'Скачать MP4',
    outputHint: 'MP4',
    featureChips: [],
  },
  {
    menuGroup: 'media',
    mediaSection: 'video',
    type: 'gif_to_mp4',
    route: '/gif-to-mp4',
    shortTitle: 'GIF → MP4',
    title: 'GIF → MP4',
    description:
      'Конвертируйте анимированные GIF в MP4, чтобы заметно уменьшить размер файла.',
    inputLabel: 'GIF',
    inputExtensions: ['.gif'],
    inputAccept: '.gif,image/gif',
    outputLabel: 'Скачать MP4',
    outputHint: 'MP4',
    featureChips: [],
  },
  {
    menuGroup: 'media',
    mediaSection: 'video',
    type: 'video_to_mp3',
    route: '/video-to-mp3',
    shortTitle: 'Видео → MP3',
    title: 'Видео → MP3',
    description:
      'Извлеките аудио-дорожку из видео и получите MP3 для музыки, лекций и подкастов.',
    inputLabel: 'Видео',
    inputExtensions: VIDEO_INPUT_EXTENSIONS,
    inputAccept: VIDEO_INPUT_ACCEPT,
    outputLabel: 'Скачать MP3',
    outputHint: 'MP3',
    featureChips: [],
  },
  {
    menuGroup: 'media',
    mediaSection: 'video',
    type: 'video_to_avi',
    route: '/video-to-avi',
    shortTitle: 'Видео → AVI',
    title: 'Видео → AVI',
    description:
      'Преобразуйте видео в AVI для совместимости со старым ПО и устройствами.',
    inputLabel: 'Видео',
    inputExtensions: VIDEO_INPUT_EXTENSIONS,
    inputAccept: VIDEO_INPUT_ACCEPT,
    outputLabel: 'Скачать AVI',
    outputHint: 'AVI',
    featureChips: [],
  },
  {
    menuGroup: 'media',
    mediaSection: 'video',
    type: 'video_to_mov',
    route: '/video-to-mov',
    shortTitle: 'Видео → MOV',
    title: 'Видео → MOV',
    description:
      'Конвертируйте видео в MOV для монтажа и рабочих пайплайнов в Apple-экосистеме.',
    inputLabel: 'Видео',
    inputExtensions: VIDEO_INPUT_EXTENSIONS,
    inputAccept: VIDEO_INPUT_ACCEPT,
    outputLabel: 'Скачать MOV',
    outputHint: 'MOV',
    featureChips: [],
  },

  {
    menuGroup: 'archiver',
    type: 'arch_zip_pack',
    route: '/archive-to-zip',
    shortTitle: 'Файлы → ZIP',
    title: 'Файлы → ZIP',
    description: 'Упакуйте один или несколько файлов в ZIP-архив для отправки и хранения.',
    inputLabel: 'Файлы',
    inputExtensions: ARCHIVE_SOURCE_EXTENSIONS,
    inputAccept: '*/*',
    allowMultiple: true,
    outputLabel: 'Скачать ZIP',
    outputHint: 'ZIP',
    featureChips: [],
  },
  {
    menuGroup: 'archiver',
    type: 'arch_7z_pack',
    route: '/archive-to-7z',
    shortTitle: 'Файлы → 7Z',
    title: 'Файлы → 7Z',
    description: 'Упакуйте файлы в 7Z с высоким уровнем сжатия.',
    inputLabel: 'Файлы',
    inputExtensions: ARCHIVE_SOURCE_EXTENSIONS,
    inputAccept: '*/*',
    allowMultiple: true,
    outputLabel: 'Скачать 7Z',
    outputHint: '7Z',
    featureChips: [],
  },
  {
    menuGroup: 'archiver',
    type: 'arch_rar_pack',
    route: '/archive-to-rar',
    shortTitle: 'Файлы → RAR',
    title: 'Файлы → RAR',
    description: 'Упакуйте файлы в RAR-архив (требуется установленный rar/WinRAR на сервере).',
    inputLabel: 'Файлы',
    inputExtensions: ARCHIVE_SOURCE_EXTENSIONS,
    inputAccept: '*/*',
    allowMultiple: true,
    outputLabel: 'Скачать RAR',
    outputHint: 'RAR',
    featureChips: [],
  },
  {
    menuGroup: 'archiver',
    type: 'arch_zip_unpack',
    route: '/unpack-zip',
    shortTitle: 'ZIP → Распаковать',
    title: 'ZIP → Распаковать',
    description: 'Распакуйте ZIP. На выходе получите ZIP с содержимым архива.',
    inputLabel: 'ZIP',
    inputExtensions: ['.zip'],
    inputAccept: '.zip,application/zip',
    outputLabel: 'Скачать ZIP (распаковано)',
    outputHint: 'ZIP',
    featureChips: [],
  },
  {
    menuGroup: 'archiver',
    type: 'arch_7z_unpack',
    route: '/unpack-7z',
    shortTitle: '7Z → Распаковать',
    title: '7Z → Распаковать',
    description: 'Распакуйте 7Z. На выходе получите ZIP с содержимым архива.',
    inputLabel: '7Z',
    inputExtensions: ['.7z'],
    inputAccept: '.7z,application/x-7z-compressed',
    outputLabel: 'Скачать ZIP (распаковано)',
    outputHint: 'ZIP',
    featureChips: [],
  },
  {
    menuGroup: 'archiver',
    type: 'arch_rar_unpack',
    route: '/unpack-rar',
    shortTitle: 'RAR → Распаковать',
    title: 'RAR → Распаковать',
    description: 'Распакуйте RAR. На выходе получите ZIP с содержимым архива.',
    inputLabel: 'RAR',
    inputExtensions: ['.rar'],
    inputAccept: '.rar,application/vnd.rar',
    outputLabel: 'Скачать ZIP (распаковано)',
    outputHint: 'ZIP',
    featureChips: [],
  },

  {
    menuGroup: 'compression',
    type: 'comp_img_jpg',
    route: '/compress-image-jpg',
    shortTitle: 'Изображение → JPG',
    title: 'Сжатие: Изображение → JPG',
    description: 'Сжать изображение с уменьшением качества и размера для веба и отправки.',
    inputLabel: 'JPG/PNG/HEIC',
    inputExtensions: ['.jpg', '.jpeg', '.png', '.heic', '.heif'],
    inputAccept: '.jpg,.jpeg,.png,.heic,.heif,image/*',
    outputLabel: 'Скачать JPG',
    outputHint: 'JPG',
    featureChips: [],
  },
  {
    menuGroup: 'compression',
    type: 'comp_img_webp',
    route: '/compress-image-webp',
    shortTitle: 'Изображение → WebP',
    title: 'Сжатие: Изображение → WebP',
    description: 'Сжать изображение и сохранить в WebP для более лёгких файлов на сайте.',
    inputLabel: 'JPG/PNG/HEIC',
    inputExtensions: ['.jpg', '.jpeg', '.png', '.heic', '.heif'],
    inputAccept: '.jpg,.jpeg,.png,.heic,.heif,image/*',
    outputLabel: 'Скачать WebP',
    outputHint: 'WebP',
    featureChips: [],
  },
  {
    menuGroup: 'compression',
    type: 'comp_img_avif',
    route: '/compress-image-avif',
    shortTitle: 'Изображение → AVIF',
    title: 'Сжатие: Изображение → AVIF',
    description: 'Сжать изображение и сохранить в AVIF для максимального уменьшения веса.',
    inputLabel: 'JPG/PNG/HEIC',
    inputExtensions: ['.jpg', '.jpeg', '.png', '.heic', '.heif'],
    inputAccept: '.jpg,.jpeg,.png,.heic,.heif,image/*',
    outputLabel: 'Скачать AVIF',
    outputHint: 'AVIF',
    featureChips: [],
  },
  {
    menuGroup: 'compression',
    type: 'comp_pdf',
    route: '/compress-pdf',
    shortTitle: 'PDF → Сжать',
    title: 'Сжатие: PDF',
    description: 'Сжать PDF за счёт оптимизации изображений и структуры документа.',
    inputLabel: 'PDF',
    inputExtensions: ['.pdf'],
    inputAccept: '.pdf,application/pdf',
    outputLabel: 'Скачать PDF',
    outputHint: 'PDF',
    featureChips: [],
  },
  {
    menuGroup: 'compression',
    type: 'comp_office_zip',
    route: '/compress-office',
    shortTitle: 'Office → ZIP',
    title: 'Сжатие: Office → ZIP',
    description: 'Упаковать Word/Excel/PowerPoint в ZIP для уменьшения веса перед отправкой.',
    inputLabel: 'DOC/XLS/PPT',
    inputExtensions: ['.doc', '.docx', '.xls', '.xlsx', '.ppt', '.pptx'],
    inputAccept: '.doc,.docx,.xls,.xlsx,.ppt,.pptx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    outputLabel: 'Скачать ZIP',
    outputHint: 'ZIP',
    featureChips: [],
  },
  {
    menuGroup: 'compression',
    type: 'comp_video_mp4',
    route: '/compress-video',
    shortTitle: 'Видео → MP4 (сжать)',
    title: 'Сжатие: Видео → MP4',
    description: 'Сжать видео через перекодирование в H.264 с уменьшением битрейта и разрешения.',
    inputLabel: 'Видео',
    inputExtensions: VIDEO_INPUT_EXTENSIONS,
    inputAccept: VIDEO_INPUT_ACCEPT,
    outputLabel: 'Скачать MP4',
    outputHint: 'MP4',
    featureChips: [],
  },
  {
    menuGroup: 'compression',
    type: 'comp_audio_mp3',
    route: '/compress-audio',
    shortTitle: 'Аудио/Видео → MP3',
    title: 'Сжатие: Аудио/Видео → MP3',
    description: 'Сжать аудио или извлечь сжатую аудио-дорожку из видео в формате MP3.',
    inputLabel: 'Аудио/Видео',
    inputExtensions: [...VIDEO_INPUT_EXTENSIONS, '.mp3', '.wav', '.m4a', '.aac', '.flac', '.ogg', '.oga', '.wma'],
    inputAccept: `${VIDEO_INPUT_ACCEPT},audio/*,.mp3,.wav,.m4a,.aac,.flac,.ogg,.oga,.wma`,
    outputLabel: 'Скачать MP3',
    outputHint: 'MP3',
    featureChips: [],
  },
]

export const CONVERSION_MAP = Object.fromEntries(
  CONVERSION_OPTIONS.map((option) => [option.type, option]),
)

export const PDF_CONVERSION_OPTIONS = CONVERSION_OPTIONS.filter((option) => option.menuGroup === 'pdf')
export const MEDIA_CONVERSION_OPTIONS = CONVERSION_OPTIONS.filter((option) => option.menuGroup === 'media')
export const MEDIA_IMAGE_CONVERSION_OPTIONS = MEDIA_CONVERSION_OPTIONS.filter((option) => option.mediaSection === 'image')
export const MEDIA_VIDEO_CONVERSION_OPTIONS = MEDIA_CONVERSION_OPTIONS.filter((option) => option.mediaSection === 'video')
export const ARCHIVER_CONVERSION_OPTIONS = CONVERSION_OPTIONS.filter((option) => option.menuGroup === 'archiver')
export const COMPRESSION_CONVERSION_OPTIONS = CONVERSION_OPTIONS.filter((option) => option.menuGroup === 'compression')

export function findConversionByRoute(pathname) {
  return CONVERSION_OPTIONS.find((option) => option.route === pathname)
}
